# Generated by Django 4.2.6 on 2023-10-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app2", "0003_alter_employee_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="Customers",
        ),
    ]
