# Generated by Django 4.2.6 on 2023-10-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("published_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("naem", models.CharField(max_length=50)),
                ("ac_no", models.IntegerField(primary_key=True, serialize=False)),
                ("mailid", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("location", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                ("qualification", models.CharField(max_length=50)),
            ],
        ),
    ]
