# Generated by Django 4.2.6 on 2023-10-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0002_rename_naem_customer_name_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
