# Generated by Django 4.2.6 on 2023-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app3", "0003_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="ac_no",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
